# Generated by Django 2.1.1 on 2018-09-29 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=100)),
                ('grado_criticidad', models.CharField(choices=[('a', 'Alta'), ('m', 'Media'), ('b', 'Baja')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Balastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=35)),
                ('grado_criticidad', models.CharField(choices=[('a', 'Alta'), ('m', 'Media'), ('b', 'Baja')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Por_Balastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Por_Insumo_Basico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Por_Lumimnaria_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Por_Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo_Basico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lampara_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('f', 'En funcionamiento'), ('d', 'Con desperfectos'), ('r', 'En Reparacion'), ('d', 'Desconectada')], default='d', max_length=1)),
                ('balastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Balastro')),
            ],
        ),
        migrations.CreateModel(
            name='Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('f', 'En funcionamiento'), ('d', 'Con desperfectos'), ('r', 'En Reparacion'), ('d', 'Desconectada')], default='d', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Marca_has_Fabricante_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Marca_has_Fabricante_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Marca_Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Marca_Luminaria_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marca_Luminaria_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Luminaria_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marca_Luminaria_NO_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.FloatField()),
                ('lampara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Luminaria_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_LED_Grupo_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo_Luminaria')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nodo_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.FloatField()),
                ('lampara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_NO_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_NO_LED_Grupo_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo_Luminaria')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nodo_NO_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion_alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alerta')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones_Orden_Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Observador_Grupo_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo_Luminaria')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('prt', 'Pendiente de revision tecnica'), ('pcf', 'Pendiente de confirmacion tecnica'), ('cna', 'Confirmacion no aprobada, pendiente de arreglo'), ('tca', 'Ticket cerrado por aprobacion'), ('tcs', 'Ticket cerrado sin aprobacion')], default='prt', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Personalizacion_Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alerta')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Balastros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Balastro')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Insumos_Basicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Insumo_Basico')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Luminaria_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Luminaria_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Luminaria_NO_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico_Grupo_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo_Luminaria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, max_length=30, verbose_name='username', validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username.', 'invalid')])),
                ('first_name', models.CharField(max_length=30, verbose_name='first name', blank=True)),
                ('last_name', models.CharField(max_length=30, verbose_name='last name', blank=True)),
                ('email', models.EmailField(max_length=75, verbose_name='email address', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios_has_rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='tecnico_grupo_luminaria',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='personalizacion_alerta',
            name='personalizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='orden_reparacion',
            name='demandante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_reparacion_requests_created', to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='orden_reparacion',
            name='falla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Falla'),
        ),
        migrations.AddField(
            model_name='orden_reparacion',
            name='tecnico_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='observador_grupo_luminaria',
            name='observador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='observaciones_orden_reparacion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='observaciones_orden_reparacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='notificacion_alerta',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='marca_has_fabricante_no_led',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marca_Luminaria_NO_LED'),
        ),
        migrations.AddField(
            model_name='marca_has_fabricante_led',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marca_Luminaria_LED'),
        ),
        migrations.AddField(
            model_name='luminaria_led',
            name='modeloLampara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Luminaria_LED'),
        ),
        migrations.AddField(
            model_name='lampara_no_led',
            name='modeloLampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Luminaria_NO_LED'),
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='gasto_por_luminaria_led',
            name='item_gastado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Luminaria_LED'),
        ),
        migrations.AddField(
            model_name='gasto_por_luminaria_led',
            name='observacion_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Observaciones_Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='gasto_por_lumimnaria_no_led',
            name='item_gastado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Luminaria_NO_LED'),
        ),
        migrations.AddField(
            model_name='gasto_por_lumimnaria_no_led',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Observaciones_Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='gasto_por_insumo_basico',
            name='item_gastado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Insumos_Basicos'),
        ),
        migrations.AddField(
            model_name='gasto_por_insumo_basico',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Observaciones_Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='gasto_por_balastro',
            name='item_gastado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Balastros'),
        ),
        migrations.AddField(
            model_name='gasto_por_balastro',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Observaciones_Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='balastro',
            name='modeloLampara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fabricante'),
        ),
    ]
