# Generated by Django 2.1.2 on 2018-11-26 05:45

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Mail')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Apellido')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=100)),
                ('periodicidad', models.CharField(choices=[('d', 'Dia'), ('h', 'Hora')], default='d', max_length=1)),
                ('frecuencia', models.PositiveIntegerField()),
                ('grado_criticidad', models.CharField(choices=[('a', 'Alta'), ('m', 'Media'), ('b', 'Baja')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Balastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=100)),
                ('potencia_desde', models.FloatField(default=0)),
                ('potencia_hasta', models.FloatField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('origen', models.CharField(default='Argentina', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=35)),
                ('grado_criticidad', models.CharField(choices=[('a', 'Alta'), ('m', 'Media'), ('b', 'Baja')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Por_Balastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Por_Insumo_Basico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Por_Lumimnaria_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Por_Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('a', 'Arreglado'), ('e', 'En reparacion'), ('p', 'Pendiente de Reparacion')], default='p', max_length=1)),
                ('asunto_mail_relevador', models.CharField(blank=True, max_length=100)),
                ('cuerpo_mail_relevador', models.CharField(blank=True, max_length=1000)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alerta')),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Falla')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente_Por_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignados', models.PositiveIntegerField()),
                ('cantidad_cerrados', models.PositiveIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente_Reparador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidente', models.ManyToManyField(to='app.Incidente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo_Basico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lampara_No_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='LAMP_NLED_', max_length=35)),
                ('es_incandecente', models.BooleanField(default='False')),
                ('estado', models.CharField(choices=[('f', 'En funcionamiento'), ('d', 'Con desperfectos'), ('r', 'En Reparacion'), ('d', 'Desconectada')], default='d', max_length=1)),
                ('balastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Balastro')),
            ],
        ),
        migrations.CreateModel(
            name='Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='LAMP_LED_', max_length=35)),
                ('estado', models.CharField(choices=[('f', 'En funcionamiento'), ('d', 'Con desperfectos'), ('r', 'En Reparacion'), ('d', 'Desconectada')], default='d', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Marca_Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('fabricante', models.ManyToManyField(to='app.Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Marca_Luminaria_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('fabricante', models.ManyToManyField(to='app.Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Marcador_Grupo_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('lat', models.CharField(max_length=35)),
                ('lng', models.CharField(max_length=35)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo_Luminaria')),
            ],
        ),
        migrations.CreateModel(
            name='Marcador_Luminaria_Led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('lat', models.CharField(max_length=35)),
                ('lng', models.CharField(max_length=35)),
                ('luminaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Luminaria_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Marcador_Luminaria_No_Led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('lat', models.CharField(max_length=35)),
                ('lng', models.CharField(max_length=35)),
                ('luminaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marca_Luminaria_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Luminaria_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marca_Luminaria_NO_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='N_LED_', max_length=35)),
                ('es_concentrador', models.BooleanField(default='False')),
                ('potencia_esperada', models.FloatField(default=0)),
                ('potencia_real', models.FloatField(default=0)),
                ('fecha_ult_medicion', models.DateField(default=datetime.date.today)),
                ('lampara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Luminaria_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='N_NLED_', max_length=35)),
                ('es_concentrador', models.BooleanField(default='False')),
                ('potencia_esperada', models.FloatField(default=0)),
                ('potencia_real', models.FloatField(default=0)),
                ('fecha_ult_medicion', models.DateField(default=datetime.date.today)),
                ('lampara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion_alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Incidente')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones_Orden_Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('prt', 'Pendiente de revision tecnica'), ('pcf', 'Pendiente de confirmacion tecnica'), ('cna', 'Confirmacion no aprobada, pendiente de arreglo'), ('tca', 'Ticket cerrado por aprobacion'), ('tcs', 'Ticket cerrado sin aprobacion')], default='prt', max_length=3)),
                ('demandante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_reparacion_requests_created', to=settings.AUTH_USER_MODEL)),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Falla')),
                ('tecnico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personalizacion_Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alerta')),
                ('personalizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('menues', models.ManyToManyField(to='app.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Balastros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Balastro')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Insumos_Basicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Insumo_Basico')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Luminaria_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Luminaria_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Luminaria_NO_LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Luminaria_NO_LED')),
            ],
        ),
        migrations.AddField(
            model_name='observaciones_orden_reparacion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='observaciones_orden_reparacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcador_grupo_luminaria',
            name='marcadoresLed',
            field=models.ManyToManyField(blank=True, to='app.Marcador_Luminaria_Led'),
        ),
        migrations.AddField(
            model_name='marcador_grupo_luminaria',
            name='marcadoresNoLed',
            field=models.ManyToManyField(blank=True, to='app.Marcador_Luminaria_No_Led'),
        ),
        migrations.AddField(
            model_name='luminaria_led',
            name='modeloLampara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Luminaria_LED'),
        ),
        migrations.AddField(
            model_name='lampara_no_led',
            name='modeloLampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Luminaria_NO_LED'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='luminaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Luminaria_LED'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='materiales',
            field=models.ManyToManyField(to='app.Material'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='relevador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='nodo_luminarias_led',
            field=models.ManyToManyField(blank=True, related_name='grupo_luminaria_led', to='app.Nodo_LED'),
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='nodo_luminarias_no_led',
            field=models.ManyToManyField(blank=True, to='app.Nodo_NO_LED'),
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='observadores',
            field=models.ManyToManyField(blank=True, related_name='observadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto_por_luminaria_led',
            name='item_gastado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Luminaria_LED'),
        ),
        migrations.AddField(
            model_name='gasto_por_luminaria_led',
            name='observacion_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Observaciones_Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='gasto_por_lumimnaria_no_led',
            name='item_gastado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Luminaria_NO_LED'),
        ),
        migrations.AddField(
            model_name='gasto_por_lumimnaria_no_led',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Observaciones_Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='gasto_por_insumo_basico',
            name='item_gastado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Insumos_Basicos'),
        ),
        migrations.AddField(
            model_name='gasto_por_insumo_basico',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Observaciones_Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='gasto_por_balastro',
            name='item_gastado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Balastros'),
        ),
        migrations.AddField(
            model_name='gasto_por_balastro',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Observaciones_Orden_Reparacion'),
        ),
        migrations.AddField(
            model_name='balastro',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fabricante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(to='app.Rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
