# Generated by Django 2.1.2 on 2018-11-26 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente_Por_Reparador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidente', models.ManyToManyField(to='app.Incidente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidente_reparador',
            name='incidente',
        ),
        migrations.RemoveField(
            model_name='incidente_reparador',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Incidente_Reparador',
        ),
    ]
