# Generated by Django 2.1.2 on 2018-10-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181011_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='luminaria_led',
            name='identificador',
            field=models.CharField(default='LAMP_LED_', max_length=35),
        ),
        migrations.AddField(
            model_name='nodo_led',
            name='es_concentrador',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='nodo_led',
            name='identificador',
            field=models.CharField(default='NOD_LED_', max_length=35),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
