# Generated by Django 2.1.2 on 2018-10-28 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181025_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_luminaria',
            name='luminaras_led',
            field=models.ManyToManyField(to='app.Luminaria_LED'),
        ),
        migrations.AddField(
            model_name='orden_reparacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
