# Generated by Django 2.1.2 on 2018-10-29 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181028_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo_luminaria',
            old_name='luminaras_led',
            new_name='luminarias_led',
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
