# Generated by Django 2.1.2 on 2018-10-29 03:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181028_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca_has_fabricante_led',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='marca_has_fabricante_led',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='marca_has_fabricante_no_led',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='marca_has_fabricante_no_led',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='nodo_led_grupo_luminaria',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='nodo_led_grupo_luminaria',
            name='nodo',
        ),
        migrations.RemoveField(
            model_name='nodo_no_led_grupo_luminaria',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='nodo_no_led_grupo_luminaria',
            name='nodo',
        ),
        migrations.RemoveField(
            model_name='observador_grupo_luminaria',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='observador_grupo_luminaria',
            name='observador',
        ),
        migrations.RemoveField(
            model_name='tecnico_grupo_luminaria',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='tecnico_grupo_luminaria',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='usuarios_has_rol',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuarios_has_rol',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='grupo_luminaria',
            name='luminarias_led',
        ),
        migrations.RemoveField(
            model_name='nodo_led',
            name='potencia',
        ),
        migrations.RemoveField(
            model_name='nodo_no_led',
            name='potencia',
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='nodo_luminarias_led',
            field=models.ManyToManyField(blank=True, to='app.Nodo_LED'),
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='nodo_luminarias_no_led',
            field=models.ManyToManyField(blank=True, to='app.Nodo_NO_LED'),
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='observadores',
            field=models.ManyToManyField(blank=True, related_name='observadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_luminaria',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marca_luminaria_led',
            name='fabricante',
            field=models.ManyToManyField(to='app.Fabricante'),
        ),
        migrations.AddField(
            model_name='marca_luminaria_no_led',
            name='fabricante',
            field=models.ManyToManyField(to='app.Fabricante'),
        ),
        migrations.AddField(
            model_name='nodo_led',
            name='fecha_ult_medicion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='nodo_led',
            name='potencia_esperada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nodo_led',
            name='potencia_real',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nodo_no_led',
            name='es_concentrador',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='nodo_no_led',
            name='fecha_ult_medicion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='nodo_no_led',
            name='identificador',
            field=models.CharField(default='N_NLED_', max_length=35),
        ),
        migrations.AddField(
            model_name='nodo_no_led',
            name='potencia_esperada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nodo_no_led',
            name='potencia_real',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='observaciones_orden_reparacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='nodo_led',
            name='identificador',
            field=models.CharField(default='N_LED_', max_length=35),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
        migrations.DeleteModel(
            name='Marca_has_Fabricante_LED',
        ),
        migrations.DeleteModel(
            name='Marca_has_Fabricante_NO_LED',
        ),
        migrations.DeleteModel(
            name='Nodo_LED_Grupo_Luminaria',
        ),
        migrations.DeleteModel(
            name='Nodo_NO_LED_Grupo_Luminaria',
        ),
        migrations.DeleteModel(
            name='Observador_Grupo_Luminaria',
        ),
        migrations.DeleteModel(
            name='Tecnico_Grupo_Luminaria',
        ),
        migrations.DeleteModel(
            name='Usuarios_has_rol',
        ),
    ]
