# Generated by Django 2.1.1 on 2018-10-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181029_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balastro',
            old_name='modeloLampara',
            new_name='fabricante',
        ),
        migrations.AddField(
            model_name='fabricante',
            name='origen',
            field=models.CharField(default='Argentina', max_length=35),
        ),
        migrations.AddField(
            model_name='lampara_no_led',
            name='es_incandecente',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='lampara_no_led',
            name='identificador',
            field=models.CharField(default='LAMP_NLED_', max_length=35),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
