# Generated by Django 2.1.1 on 2018-10-29 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181029_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('ar', 'Arreglado'), ('er', 'En reparacion'), ('pr', 'Pendiente de Reparacion')], default='pr', max_length=1)),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Falla')),
                ('luminaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Luminaria_LED')),
                ('relevador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
