# Generated by Django 2.1.1 on 2018-10-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181029_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(choices=[('a', 'Arreglado'), ('e', 'En reparacion'), ('p', 'Pendiente de Reparacion')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
