# Generated by Django 2.1.2 on 2018-10-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181029_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=100)),
                ('potencia_desde', models.FloatField(default=0)),
                ('potencia_hasta', models.FloatField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
