# Generated by Django 2.1.1 on 2018-11-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181029_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcador_Grupo_Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('lat', models.CharField(max_length=35)),
                ('lng', models.CharField(max_length=35)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo_Luminaria')),
            ],
        ),
        migrations.CreateModel(
            name='Marcador_Luminaria_Led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('lat', models.CharField(max_length=35)),
                ('lng', models.CharField(max_length=35)),
                ('luminaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Luminaria_LED')),
            ],
        ),
        migrations.CreateModel(
            name='Marcador_Luminaria_No_Led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('lat', models.CharField(max_length=35)),
                ('lng', models.CharField(max_length=35)),
                ('luminaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED')),
            ],
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
        migrations.AddField(
            model_name='marcador_grupo_luminaria',
            name='marcadoresLed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marcador_Luminaria_Led'),
        ),
        migrations.AddField(
            model_name='marcador_grupo_luminaria',
            name='marcadoresNoLed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marcador_Luminaria_No_Led'),
        ),
    ]
