# Generated by Django 2.1.2 on 2018-11-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181029_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='grupo_luminaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Grupo_Luminaria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
