# Generated by Django 2.1.2 on 2018-11-07 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181107_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_luminaria',
            name='nodo_luminarias_led',
            field=models.ManyToManyField(blank=True, related_name='grupo_luminaria_led', to='app.Nodo_LED'),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
