# Generated by Django 2.1.2 on 2018-11-11 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181107_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='tiempo',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
