# Generated by Django 2.1.2 on 2018-11-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20181111_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='grupo_luminaria',
        ),
        migrations.AddField(
            model_name='incidente',
            name='alerta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Alerta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
