# Generated by Django 2.1.2 on 2018-11-11 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20181111_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=4000)),
            ],
        ),
        migrations.RemoveField(
            model_name='notificacion_alerta',
            name='asunto',
        ),
        migrations.AddField(
            model_name='notificacion_alerta',
            name='fecha_envio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
