# Generated by Django 2.1.2 on 2018-11-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20181112_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
