# Generated by Django 2.1.2 on 2018-11-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20181112_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='asunto_mail_relevador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incidente',
            name='cuerpo_mail_relevador',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='marcador_luminaria_no_led',
            name='luminaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
