# Generated by Django 2.1.2 on 2018-11-26 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20181126_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion_alerta',
            name='alerta',
        ),
        migrations.RemoveField(
            model_name='notificacion_alerta',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='notificacion_alerta',
            name='incidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Incidente'),
        ),
        migrations.AlterField(
            model_name='marcador_luminaria_no_led',
            name='luminaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
        migrations.AlterField(
            model_name='nodo_no_led',
            name='lampara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lampara_No_LED'),
        ),
    ]
